### ISSUE TITLE
Can you share some code or give me some help?

### ISSUE THREAD

**Issue by JiuqingDong** [SCUTjinchengli/test#1]
Hi, I am a PhD student. I saw your comment about this paper: F-VLM: Open-Vocabulary Object Detection upon Frozen Vision and Language Models
https://openreview.net/forum?id=MIMwy4kh9lf&noteId=9FfSfVS_sK

Maybe you reimplement the code for this paper. I want to know how did you process the image resolution? The default resolution of CLIP is 224x224, but 1024x1024 in this paper. There is a domain gap. 

Looking forward to your reply. Thank your very much.

**Comment by SCUTjinchengli** [comment]
hi, official code demo: 
https://github.com/google-research/google-research/tree/master/fvlm

**Comment by JiuqingDong** [comment]
Oh, thank you very much! I will learn it.

SCUTjinchengli ***@***.***> 于2023年5月8日周一 17:06写道：
